import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Trip Planner",
  description: "Generated by create next app",
};
import { Noto_Sans_Thai } from "next/font/google";
import { Link, Navbar, NavbarContent, NavbarItem } from "@nextui-org/react";

const notosans = Noto_Sans_Thai({ subsets: ["thai"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notosans.className}>
        <Providers>
          <Navbar isBordered>
            <NavbarContent justify="start"></NavbarContent>
            <NavbarContent justify="center">
              <NavbarItem>
                <Link color="foreground" href="/">
                  หน้าหลัก
                </Link>
              </NavbarItem>
              <NavbarItem>
                <Link color="foreground" href="/edit">
                  วางแผน
                </Link>
              </NavbarItem>
            </NavbarContent>
            <NavbarContent justify="end"></NavbarContent>
          </Navbar>
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
