import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Trip Planner",
  description: "Generated by create next app",
};
import { Noto_Sans_Thai } from "next/font/google";

const notosans = Noto_Sans_Thai({ subsets: ["thai"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notosans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
